#!/usr/bin/env python
"""Stage 7 -- the 2x2 table (base/tuned x text/vision), split by seen/unseen/real.

Reads every outputs/*/<run>/eval-{base,tuned}.jsonl and writes a Markdown report: docs/RESULTS.md
for the full run, outputs/report-<run>.md for smoke. The headline number is real_test;
synthetic numbers are reported beside it, never instead of it.

Lists are micro-averaged (summed tp/fp/fn over the split), scalars are mean exact-match.
Format failures are already scored against an empty resume by stage 6.
"""

from __future__ import annotations

import argparse
import collections
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from cvx.config import load_data_config  # noqa: E402
from cvx.metrics import SCALARS  # noqa: E402

LISTS = ("experiencias", "experiencia_datas", "formacao", "habilidades", "idiomas")
SPLIT_ORDER = ("real_test", "test_unseen", "test_seen")


def f1(tp: int, fp: int, fn: int) -> float:
    p = tp / (tp + fp) if tp + fp else 1.0
    r = tp / (tp + fn) if tp + fn else 1.0
    return 2 * p * r / (p + r) if p + r else 0.0


def aggregate(rows: list[dict]) -> dict:
    n = len(rows)
    out = {"n": n, "json_ok": sum(r["error"] is None for r in rows) / n}
    for name in SCALARS:
        out[name] = sum(r["score"]["scalars"][name] for r in rows) / n
    out["scalars"] = sum(out[name] for name in SCALARS) / len(SCALARS)
    for name in LISTS:
        tot = collections.Counter()
        for r in rows:
            tot.update(r["score"][name])
        out[name] = f1(tot["tp"], tot["fp"], tot["fn"])
    extracted = sum(r["score"]["extracted_values"] for r in rows)
    out["halluc"] = sum(r["score"]["hallucinated"] for r in rows) / extracted if extracted else 0.0
    out["errors"] = dict(collections.Counter(r["error"] for r in rows if r["error"]))
    out["latency_s"] = sum(r["latency_s"] for r in rows) / n
    return out


def pct(x: float) -> str:
    return f"{100 * x:.1f}"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--data-config", default="configs/data.yaml")
    parser.add_argument("--smoke", action="store_true", help="report the smoke run")
    parser.add_argument("--out", default=None)
    args = parser.parse_args()
    data = load_data_config(args.data_config)
    run = data.smoke.run if args.smoke else data.generate.run
    out = Path(args.out or ("docs/RESULTS.md" if not args.smoke else f"outputs/report-{run}.md"))

    groups: dict[tuple, list[dict]] = collections.defaultdict(list)
    # Exactly eval-base / eval-tuned: partial runs and backups beside them would double-count.
    sources = sorted(p for which in ("base", "tuned")
                     for p in Path("outputs").glob(f"*/{run}/eval-{which}.jsonl"))
    for path in sources:
        for line in path.read_text(encoding="utf-8").splitlines():
            r = json.loads(line)
            groups[(r["split"], r["modality"], r["which"], r["mode"])].append(r)
    if not groups:
        print(f"FATAL: no outputs/*/{run}/eval-{{base,tuned}}.jsonl", file=sys.stderr)
        return 1

    def order(key: tuple) -> tuple:
        split, modality, which, mode = key
        return (SPLIT_ORDER.index(split) if split in SPLIT_ORDER else 9, modality,
                which != "base", mode)

    keys = sorted(groups, key=order)
    aggs = {k: aggregate(groups[k]) for k in keys}

    lines = [
        f"# Results -- run `{run}`",
        "",
        "Generated by `scripts/07_report.py` from:",
        "",
        *[f"- `{p}`" for p in sources],
        "",
        "Percentages. *JSON ok*: parsed and schema-valid, not truncated. *Scalars*: mean",
        "exact-match over " + ", ".join(SCALARS) + ". List columns: micro F1; *exp dates* is",
        "scored on matched experiences only. *Halluc.*: grounded values absent from the",
        "source text (lower is better). `real_test` is the headline when present.",
        "",
        "| split | modality | model | mode | n | JSON ok | scalars | exp F1 | exp dates "
        "| edu F1 | skills F1 | lang F1 | halluc. | s/req |",
        "|---|---|---|---|--:|--:|--:|--:|--:|--:|--:|--:|--:|--:|",
    ]
    for k in keys:
        a = aggs[k]
        lines.append("| " + " | ".join([*k, str(a["n"]), pct(a["json_ok"]), pct(a["scalars"]),
                                         *(pct(a[n]) for n in LISTS), pct(a["halluc"]),
                                         f"{a['latency_s']:.1f}"]) + " |")

    lines += ["", "## Scalar fields", "",
              "| split | modality | model | mode | " + " | ".join(SCALARS) + " |",
              "|---|---|---|---|" + "--:|" * len(SCALARS)]
    for k in keys:
        lines.append("| " + " | ".join([*k, *(pct(aggs[k][n]) for n in SCALARS)]) + " |")

    lines += ["", "## Format failures", "", "| split | modality | model | mode | errors |",
              "|---|---|---|---|---|"]
    for k in keys:
        errs = ", ".join(f"{e}: {c}" for e, c in sorted(aggs[k]["errors"].items())) or "--"
        lines.append("| " + " | ".join([*k, errs]) + " |")

    by_template: dict[tuple, list[dict]] = collections.defaultdict(list)
    for (split, modality, which, mode), rows in groups.items():
        if mode == "grammar":
            for r in rows:
                by_template[(r["template"], modality, which)].append(r)
    lines += ["", "## Per template (grammar mode)", "",
              "| template | modality | model | n | scalars | exp F1 | exp dates | edu F1 |",
              "|---|---|---|--:|--:|--:|--:|--:|"]
    for k in sorted(by_template, key=lambda k: (k[0], k[1], k[2] != "base")):
        a = aggregate(by_template[k])
        lines.append("| " + " | ".join([*k, str(a["n"]), pct(a["scalars"]),
                                         pct(a["experiencias"]), pct(a["experiencia_datas"]),
                                         pct(a["formacao"])]) + " |")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f">> wrote {out}")
    main_table = lines.index("## Scalar fields") - 1
    print("\n".join(lines[main_table - len(keys) - 2: main_table]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
